### ISSUE TITLE
internal_server_error

### ISSUE THREAD

**Issue by rafalwawrzyk** [wp-graphql/wp-graphql-custom-post-type-ui#12]
Hello, i saw you make plugin update today but after that i have internal_server_error

![image](https://user-images.githubusercontent.com/24826622/108495641-57064400-72a9-11eb-97d0-488b0361d479.png)

**Comment by rafalwawrzyk** [comment]
I found the bug. I've make error when adding post type. I have same plural and singular label and this caused the probem

**Comment by stevepepple** [comment]
I'm also seeing this issue, and don't think it's because of the plural / singular label issue. 

(When I disable custom post type I see see the issue and it doesn't show any debug or trace)

Attached are the versions of the plugins I'm using. 
![Uploading Screen Shot 2021-02-19 at 11.44.23 AM.png…]()
