### ISSUE TITLE
Doesn't work with CPT UI 1.8.2 

### ISSUE THREAD

**Issue by Yuribtr** [wp-graphql/wp-graphql-custom-post-type-ui#14]
Seems that latest update CPT UI (to version 1.8.2) breaks schema generation at GraphiQL IDE (page /wp-admin/admin.php?page=graphiql-ide). When this plugin activated, the Explorer window in GraphiQL IDE became empty and in developer console I see following error:

> Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }
main.b7d08b5b.js:1:199854
https://........./wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1

**Comment by jasonbahl** [comment]
👋  I just pushed [v1.2.0](https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/releases/tag/v1.2.0) which makes several improvements. 

There was a bug that allowed you to leave the `graphql_single_name` and `graphql_plural_name` values empty, and that causes issues with the Schema registration. 

This plugin has been updated so that those fields are hidden if `show_in_graphql` is false, and shown and required if set to true. 

I'm running CPT UI 1.8.2 and v1.2.0 of this plugin currently and the issues have been resolved for me. 

If you're experiencing issues still, please open another issue, reference this one, and add any additional details you can to make it easy to replicate.
