### ISSUE TITLE
Show in GraphQL select is always true

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql-custom-post-type-ui#8]
If you set it to false, it will still say true when the page refreshes.
Tried on pre-0.4.0 & 0.4.0

**Comment by jasonbahl** [comment]
This has been fixed in the v1.2.0 release. 

Default is now false. users must opt-in to show_in_graphql, then they are required to add the graphql_single_name and graphql_plural_name

![show-in-graphql-cptui](https://user-images.githubusercontent.com/1260765/112374452-bc35c680-8ca7-11eb-8116-f0372022687e.gif)
